#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu:ubuntu /var/www
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
